//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "badges")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub crate_id: i32,
    #[sea_orm(primary_key, auto_increment = false)]
    pub badge_type: String,
    pub attributes: Json,
}

#[derive(Copy, Clone, Debug, EnumIter)]
pub enum Relation {}

impl RelationTrait for Relation {
    fn def(&self) -> RelationDef {
        panic!("No RelationDef")
    }
}

impl ActiveModelBehavior for ActiveModel {}
