//! SeaORM Entity. Generated by sea-orm-codegen 0.9.2

pub mod prelude;


pub mod badges;
pub mod categories;
pub mod crates;
pub mod crates_categories;
pub mod crates_keywords;
pub mod keywords;
pub mod metadata;
pub mod reserved_crate_names;
pub mod versions;
pub mod sync_history;

